trigger:
  batch: true

jobs:
- job: CDelivery
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3'
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    inputs:
      command: 'run'
      projects: '**/WalletWasabi.Packager.csproj'
      arguments: '--cdelivery'
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'WalletWasabi.Gui/bin/dist/cdelivery/'
      contents: '**'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: WasabiBuildOutputs
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_molnard'
      repositoryName: 'molnard/WasabiDeploy'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v1.0'
      title: 'Wasabi binaries'
      releaseNotesSource: 'inline'
      releaseNotesInline: 'Hello world'
      isPreRelease: true
      addChangeLog: false
