# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  testConfiguration: 'Debug'
  
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.101'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Debug
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Release
   - task: DotNetCoreCLI@2
    inputs:
      command: test
      arguments: --filter Category=RunOnCi --configuration $(testConfiguration)
    
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.101'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Debug
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Release
   - task: DotNetCoreCLI@2
    inputs:
      command: test
      arguments: --filter Category=RunOnCi --configuration $(testConfiguration)
  
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.101'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Debug
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Release
   - task: DotNetCoreCLI@2
    inputs:
      command: test
      arguments: --filter Category=RunOnCi --configuration $(testConfiguration)
