# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  buildConfiguration: 'Debug'
  
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
  
  - task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'WalletWasabi.Tests/WalletWasabi.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
- job: macOS
  pool:
    vmImage: 'macos10.13'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    
  - task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'WalletWasabi.Tests/WalletWasabi.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
  
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    
  - task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'WalletWasabi.Tests/WalletWasabi.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
