variables:
  testConfiguration: 'Debug'

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 2.2.402
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: Build debug
    inputs:
      command: build
      arguments: --configuration Debug --no-incremental
  - task: Build release
    inputs:
      command: build
      arguments: --configuration Release --no-incremental
  - task: Run tests
    inputs:
      command: test
      projects: 'WalletWasabi.Tests/WalletWasabi.Tests.csproj'
      arguments: --configuration $(testConfiguration) --filter "UnitTests"
