variables:
  testConfiguration: 'Debug'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.101'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Debug
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Release
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'WalletWasabi.Tests/WalletWasabi.Tests.csproj'	
      arguments: --filter Category=RunOnCi --configuration $(testConfiguration)
